export interface Product {
  id: number
  name: string
  description: string
  price: number
  category: string
  image: string
  badge: string | null
  fullDescription?: string
  features?: string[]
  specifications?: { label: string; value: string }[]
  inStock?: boolean
  rating?: number
  reviews?: number
}

export const products: Product[] = [
  {
    id: 1,
    name: "Wireless Headphones",
    description: "Premium noise-cancelling headphones with 30-hour battery life",
    fullDescription:
      "Experience superior sound quality with our premium wireless headphones. Featuring advanced active noise cancellation technology, these headphones deliver an immersive audio experience whether you're commuting, working, or relaxing. The comfortable over-ear design ensures all-day wearability, while the impressive 30-hour battery life keeps you connected without interruption.",
    price: 299.99,
    category: "Electronics",
    image: "/wireless-headphones.png",
    badge: "Best Seller",
    inStock: true,
    rating: 4.8,
    reviews: 1247,
    features: [
      "Active Noise Cancellation (ANC)",
      "30-hour battery life",
      "Bluetooth 5.0 connectivity",
      "Premium memory foam ear cushions",
      "Foldable design with carrying case",
      "Built-in microphone for calls",
    ],
    specifications: [
      { label: "Driver Size", value: "40mm" },
      { label: "Frequency Response", value: "20Hz - 20kHz" },
      { label: "Impedance", value: "32 Ohms" },
      { label: "Weight", value: "250g" },
      { label: "Charging Time", value: "2 hours" },
      { label: "Wireless Range", value: "10 meters" },
    ],
  },
  {
    id: 2,
    name: "Smart Watch Pro",
    description: "Advanced fitness tracking with heart rate monitor and GPS",
    fullDescription:
      "Stay connected and track your fitness goals with the Smart Watch Pro. This advanced wearable combines cutting-edge health monitoring technology with smart notifications and GPS tracking. Whether you're running, cycling, or swimming, this watch is your perfect companion for an active lifestyle.",
    price: 399.99,
    category: "Electronics",
    image: "/smartwatch-lifestyle.png",
    badge: "New",
    inStock: true,
    rating: 4.6,
    reviews: 892,
    features: [
      "Heart rate monitoring 24/7",
      "Built-in GPS tracking",
      "Water resistant up to 50m",
      "Sleep tracking and analysis",
      "Multiple sport modes",
      "7-day battery life",
    ],
    specifications: [
      { label: "Display", value: '1.4" AMOLED' },
      { label: "Resolution", value: "454 x 454 pixels" },
      { label: "Battery", value: "300mAh" },
      { label: "Connectivity", value: "Bluetooth 5.0, Wi-Fi" },
      { label: "Sensors", value: "Heart rate, GPS, Accelerometer, Gyroscope" },
      { label: "Compatibility", value: "iOS 12+, Android 6+" },
    ],
  },
  {
    id: 3,
    name: "Leather Backpack",
    description: "Handcrafted genuine leather backpack with laptop compartment",
    fullDescription:
      "Crafted from premium full-grain leather, this backpack combines timeless style with modern functionality. The spacious interior features a dedicated padded laptop compartment, multiple organizational pockets, and comfortable padded straps. Perfect for professionals, students, and travelers who appreciate quality craftsmanship.",
    price: 159.99,
    category: "Accessories",
    image: "/brown-leather-backpack.png",
    badge: null,
    inStock: true,
    rating: 4.7,
    reviews: 543,
    features: [
      "Genuine full-grain leather",
      'Padded laptop compartment (fits up to 15")',
      "Multiple interior pockets",
      "Adjustable padded shoulder straps",
      "Top carry handle",
      "Antique brass hardware",
    ],
    specifications: [
      { label: "Material", value: "Full-grain leather" },
      { label: "Dimensions", value: '16" x 12" x 6"' },
      { label: "Laptop Compartment", value: "Up to 15 inches" },
      { label: "Weight", value: "1.2kg" },
      { label: "Closure", value: "Drawstring with flap" },
      { label: "Care", value: "Leather conditioner recommended" },
    ],
  },
  {
    id: 4,
    name: "Mechanical Keyboard",
    description: "RGB backlit mechanical keyboard with custom switches",
    fullDescription:
      "Elevate your typing experience with this premium mechanical keyboard. Featuring customizable RGB backlighting, hot-swappable switches, and a durable aluminum frame, this keyboard is designed for gamers and professionals who demand the best. The tactile feedback and satisfying click of mechanical switches will transform your workflow.",
    price: 179.99,
    category: "Electronics",
    image: "/mechanical-keyboard.png",
    badge: "Popular",
    inStock: true,
    rating: 4.9,
    reviews: 2103,
    features: [
      "Hot-swappable mechanical switches",
      "Per-key RGB backlighting",
      "Aluminum alloy frame",
      "N-key rollover",
      "Detachable USB-C cable",
      "Programmable keys with software",
    ],
    specifications: [
      { label: "Switch Type", value: "Cherry MX Red (Hot-swappable)" },
      { label: "Layout", value: "Full-size (104 keys)" },
      { label: "Connection", value: "USB-C (wired)" },
      { label: "Polling Rate", value: "1000Hz" },
      { label: "Keycaps", value: "Double-shot PBT" },
      { label: "Dimensions", value: '17.5" x 5.5" x 1.5"' },
    ],
  },
  {
    id: 5,
    name: "Running Shoes",
    description: "Lightweight performance running shoes with cushioned sole",
    fullDescription:
      "Designed for runners who demand comfort and performance, these lightweight running shoes feature advanced cushioning technology and breathable mesh construction. The responsive midsole provides excellent energy return, while the durable outsole offers superior traction on various surfaces.",
    price: 129.99,
    category: "Footwear",
    image: "/running-shoes.jpg",
    badge: null,
    inStock: true,
    rating: 4.5,
    reviews: 678,
    features: [
      "Breathable mesh upper",
      "Responsive foam midsole",
      "Durable rubber outsole",
      "Reflective details for visibility",
      "Lightweight design (8.5 oz per shoe)",
      "Removable insole",
    ],
    specifications: [
      { label: "Weight", value: "8.5 oz (Men's size 9)" },
      { label: "Drop", value: "8mm" },
      { label: "Upper Material", value: "Engineered mesh" },
      { label: "Midsole", value: "EVA foam" },
      { label: "Outsole", value: "Rubber with flex grooves" },
      { label: "Sizes Available", value: "US 6-14" },
    ],
  },
  {
    id: 6,
    name: "Coffee Maker",
    description: "Programmable coffee maker with thermal carafe",
    fullDescription:
      "Wake up to the perfect cup of coffee every morning with this programmable coffee maker. The thermal carafe keeps your coffee hot for hours without a heating plate, preserving the rich flavor and aroma. With customizable brew strength and a convenient timer, you can enjoy barista-quality coffee at home.",
    price: 89.99,
    category: "Home",
    image: "/modern-coffee-maker.png",
    badge: "Sale",
    inStock: true,
    rating: 4.4,
    reviews: 1456,
    features: [
      "Programmable 24-hour timer",
      "Thermal carafe keeps coffee hot for 4+ hours",
      "Adjustable brew strength",
      "Auto shut-off feature",
      "Permanent gold-tone filter included",
      "12-cup capacity",
    ],
    specifications: [
      { label: "Capacity", value: "12 cups (60 oz)" },
      { label: "Carafe Type", value: "Double-wall thermal stainless steel" },
      { label: "Power", value: "1000W" },
      { label: "Dimensions", value: '9" x 8" x 14"' },
      { label: "Filter Type", value: "Permanent gold-tone (included)" },
      { label: "Warranty", value: "2 years" },
    ],
  },
  {
    id: 7,
    name: "Yoga Mat",
    description: "Non-slip eco-friendly yoga mat with carrying strap",
    fullDescription:
      "Practice yoga in comfort and style with this premium eco-friendly yoga mat. Made from sustainable materials, this mat provides excellent grip and cushioning for all types of yoga and floor exercises. The non-slip surface ensures stability during your practice, while the included carrying strap makes it easy to transport.",
    price: 49.99,
    category: "Fitness",
    image: "/rolled-yoga-mat.png",
    badge: null,
    inStock: true,
    rating: 4.6,
    reviews: 892,
    features: [
      "Eco-friendly TPE material",
      "Non-slip textured surface",
      "6mm thick for optimal cushioning",
      "Lightweight and portable",
      "Free from harmful chemicals",
      "Includes carrying strap",
    ],
    specifications: [
      { label: "Material", value: "TPE (Thermoplastic Elastomer)" },
      { label: "Thickness", value: "6mm" },
      { label: "Dimensions", value: '72" x 24"' },
      { label: "Weight", value: "2.2 lbs" },
      { label: "Texture", value: "Double-sided non-slip" },
      { label: "Care", value: "Wipe clean with damp cloth" },
    ],
  },
  {
    id: 8,
    name: "Desk Lamp",
    description: "LED desk lamp with adjustable brightness and color temperature",
    fullDescription:
      "Illuminate your workspace with this modern LED desk lamp. Featuring adjustable brightness levels and color temperature settings, you can customize the lighting to suit any task or mood. The sleek design and flexible arm allow you to direct light exactly where you need it, while the energy-efficient LED technology saves power.",
    price: 69.99,
    category: "Home",
    image: "/modern-desk-lamp.png",
    badge: null,
    inStock: true,
    rating: 4.7,
    reviews: 734,
    features: [
      "5 brightness levels",
      "3 color temperature modes (warm, neutral, cool)",
      "Flexible gooseneck arm",
      "Touch-sensitive controls",
      "USB charging port",
      "Energy-efficient LED (50,000 hour lifespan)",
    ],
    specifications: [
      { label: "Power", value: "12W LED" },
      { label: "Brightness", value: "Up to 1000 lumens" },
      { label: "Color Temperature", value: "3000K - 6000K" },
      { label: "Arm Length", value: "16 inches" },
      { label: "Base Dimensions", value: '7" diameter' },
      { label: "Power Source", value: "AC adapter (included)" },
    ],
  },
  {
    id: 9,
    name: "Wireless Mouse",
    description: "Ergonomic wireless mouse with precision tracking",
    fullDescription:
      "Experience comfort and precision with this ergonomic wireless mouse. Designed to reduce hand strain during extended use, this mouse features a contoured shape that fits naturally in your hand. The high-precision optical sensor ensures accurate tracking on various surfaces, while the wireless connectivity eliminates cable clutter.",
    price: 59.99,
    category: "Electronics",
    image: "/wireless-mouse.png",
    badge: "Best Seller",
    inStock: true,
    rating: 4.6,
    reviews: 1823,
    features: [
      "Ergonomic contoured design",
      "High-precision optical sensor (1600 DPI)",
      "Wireless 2.4GHz connection",
      "6 programmable buttons",
      "Long battery life (up to 18 months)",
      "Compatible with Windows and Mac",
    ],
    specifications: [
      { label: "Sensor", value: "Optical, 1600 DPI" },
      { label: "Connectivity", value: "2.4GHz wireless (USB receiver)" },
      { label: "Buttons", value: "6 programmable" },
      { label: "Battery", value: "1 AA (included)" },
      { label: "Dimensions", value: '4.7" x 2.8" x 1.6"' },
      { label: "Weight", value: "3.5 oz (without battery)" },
    ],
  },
]
