/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TermsImport } from './routes/terms'
import { Route as PrivacyImport } from './routes/privacy'
import { Route as AuthedImport } from './routes/_authed'
import { Route as IndexImport } from './routes/index'
import { Route as CoffeeShopsSlugImport } from './routes/coffee-shops.$slug'
import { Route as AuthedCompleteRegistrationImport } from './routes/_authed/complete-registration'
import { Route as authenticationResetPasswordImport } from './routes/(authentication)/reset-password'
import { Route as authenticationRegisterImport } from './routes/(authentication)/register'
import { Route as authenticationLoginImport } from './routes/(authentication)/login'
import { Route as authenticationForgotPasswordImport } from './routes/(authentication)/forgot-password'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard/route'
import { Route as AuthedDashboardIndexImport } from './routes/_authed/dashboard/index'
import { Route as AuthedDashboardSettingsImport } from './routes/_authed/dashboard/settings'
import { Route as AuthedDashboardManagementSpacesImport } from './routes/_authed/dashboard/management/spaces'
import { Route as AuthedDashboardManagementSetupImport } from './routes/_authed/dashboard/management/setup'
import { Route as AuthedDashboardManagementReservationsImport } from './routes/_authed/dashboard/management/reservations'
import { Route as AuthedDashboardManagementPackagesImport } from './routes/_authed/dashboard/management/packages'
import { Route as AuthedDashboardManagementEventsImport } from './routes/_authed/dashboard/management/events'

// Create/Update Routes

const TermsRoute = TermsImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRoute,
} as any)

const PrivacyRoute = PrivacyImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRoute,
} as any)

const AuthedRoute = AuthedImport.update({
  id: '/_authed',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CoffeeShopsSlugRoute = CoffeeShopsSlugImport.update({
  id: '/coffee-shops/$slug',
  path: '/coffee-shops/$slug',
  getParentRoute: () => rootRoute,
} as any)

const AuthedCompleteRegistrationRoute = AuthedCompleteRegistrationImport.update(
  {
    id: '/complete-registration',
    path: '/complete-registration',
    getParentRoute: () => AuthedRoute,
  } as any,
)

const authenticationResetPasswordRoute =
  authenticationResetPasswordImport.update({
    id: '/(authentication)/reset-password',
    path: '/reset-password',
    getParentRoute: () => rootRoute,
  } as any)

const authenticationRegisterRoute = authenticationRegisterImport.update({
  id: '/(authentication)/register',
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const authenticationLoginRoute = authenticationLoginImport.update({
  id: '/(authentication)/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const authenticationForgotPasswordRoute =
  authenticationForgotPasswordImport.update({
    id: '/(authentication)/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => rootRoute,
  } as any)

const AuthedDashboardRouteRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedDashboardIndexRoute = AuthedDashboardIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedDashboardRouteRoute,
} as any)

const AuthedDashboardSettingsRoute = AuthedDashboardSettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedDashboardRouteRoute,
} as any)

const AuthedDashboardManagementSpacesRoute =
  AuthedDashboardManagementSpacesImport.update({
    id: '/management/spaces',
    path: '/management/spaces',
    getParentRoute: () => AuthedDashboardRouteRoute,
  } as any)

const AuthedDashboardManagementSetupRoute =
  AuthedDashboardManagementSetupImport.update({
    id: '/management/setup',
    path: '/management/setup',
    getParentRoute: () => AuthedDashboardRouteRoute,
  } as any)

const AuthedDashboardManagementReservationsRoute =
  AuthedDashboardManagementReservationsImport.update({
    id: '/management/reservations',
    path: '/management/reservations',
    getParentRoute: () => AuthedDashboardRouteRoute,
  } as any)

const AuthedDashboardManagementPackagesRoute =
  AuthedDashboardManagementPackagesImport.update({
    id: '/management/packages',
    path: '/management/packages',
    getParentRoute: () => AuthedDashboardRouteRoute,
  } as any)

const AuthedDashboardManagementEventsRoute =
  AuthedDashboardManagementEventsImport.update({
    id: '/management/events',
    path: '/management/events',
    getParentRoute: () => AuthedDashboardRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedImport
      parentRoute: typeof rootRoute
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyImport
      parentRoute: typeof rootRoute
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsImport
      parentRoute: typeof rootRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedImport
    }
    '/(authentication)/forgot-password': {
      id: '/(authentication)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authenticationForgotPasswordImport
      parentRoute: typeof rootRoute
    }
    '/(authentication)/login': {
      id: '/(authentication)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authenticationLoginImport
      parentRoute: typeof rootRoute
    }
    '/(authentication)/register': {
      id: '/(authentication)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authenticationRegisterImport
      parentRoute: typeof rootRoute
    }
    '/(authentication)/reset-password': {
      id: '/(authentication)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authenticationResetPasswordImport
      parentRoute: typeof rootRoute
    }
    '/_authed/complete-registration': {
      id: '/_authed/complete-registration'
      path: '/complete-registration'
      fullPath: '/complete-registration'
      preLoaderRoute: typeof AuthedCompleteRegistrationImport
      parentRoute: typeof AuthedImport
    }
    '/coffee-shops/$slug': {
      id: '/coffee-shops/$slug'
      path: '/coffee-shops/$slug'
      fullPath: '/coffee-shops/$slug'
      preLoaderRoute: typeof CoffeeShopsSlugImport
      parentRoute: typeof rootRoute
    }
    '/_authed/dashboard/settings': {
      id: '/_authed/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthedDashboardSettingsImport
      parentRoute: typeof AuthedDashboardRouteImport
    }
    '/_authed/dashboard/': {
      id: '/_authed/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthedDashboardIndexImport
      parentRoute: typeof AuthedDashboardRouteImport
    }
    '/_authed/dashboard/management/events': {
      id: '/_authed/dashboard/management/events'
      path: '/management/events'
      fullPath: '/dashboard/management/events'
      preLoaderRoute: typeof AuthedDashboardManagementEventsImport
      parentRoute: typeof AuthedDashboardRouteImport
    }
    '/_authed/dashboard/management/packages': {
      id: '/_authed/dashboard/management/packages'
      path: '/management/packages'
      fullPath: '/dashboard/management/packages'
      preLoaderRoute: typeof AuthedDashboardManagementPackagesImport
      parentRoute: typeof AuthedDashboardRouteImport
    }
    '/_authed/dashboard/management/reservations': {
      id: '/_authed/dashboard/management/reservations'
      path: '/management/reservations'
      fullPath: '/dashboard/management/reservations'
      preLoaderRoute: typeof AuthedDashboardManagementReservationsImport
      parentRoute: typeof AuthedDashboardRouteImport
    }
    '/_authed/dashboard/management/setup': {
      id: '/_authed/dashboard/management/setup'
      path: '/management/setup'
      fullPath: '/dashboard/management/setup'
      preLoaderRoute: typeof AuthedDashboardManagementSetupImport
      parentRoute: typeof AuthedDashboardRouteImport
    }
    '/_authed/dashboard/management/spaces': {
      id: '/_authed/dashboard/management/spaces'
      path: '/management/spaces'
      fullPath: '/dashboard/management/spaces'
      preLoaderRoute: typeof AuthedDashboardManagementSpacesImport
      parentRoute: typeof AuthedDashboardRouteImport
    }
  }
}

// Create and export the route tree

interface AuthedDashboardRouteRouteChildren {
  AuthedDashboardSettingsRoute: typeof AuthedDashboardSettingsRoute
  AuthedDashboardIndexRoute: typeof AuthedDashboardIndexRoute
  AuthedDashboardManagementEventsRoute: typeof AuthedDashboardManagementEventsRoute
  AuthedDashboardManagementPackagesRoute: typeof AuthedDashboardManagementPackagesRoute
  AuthedDashboardManagementReservationsRoute: typeof AuthedDashboardManagementReservationsRoute
  AuthedDashboardManagementSetupRoute: typeof AuthedDashboardManagementSetupRoute
  AuthedDashboardManagementSpacesRoute: typeof AuthedDashboardManagementSpacesRoute
}

const AuthedDashboardRouteRouteChildren: AuthedDashboardRouteRouteChildren = {
  AuthedDashboardSettingsRoute: AuthedDashboardSettingsRoute,
  AuthedDashboardIndexRoute: AuthedDashboardIndexRoute,
  AuthedDashboardManagementEventsRoute: AuthedDashboardManagementEventsRoute,
  AuthedDashboardManagementPackagesRoute:
    AuthedDashboardManagementPackagesRoute,
  AuthedDashboardManagementReservationsRoute:
    AuthedDashboardManagementReservationsRoute,
  AuthedDashboardManagementSetupRoute: AuthedDashboardManagementSetupRoute,
  AuthedDashboardManagementSpacesRoute: AuthedDashboardManagementSpacesRoute,
}

const AuthedDashboardRouteRouteWithChildren =
  AuthedDashboardRouteRoute._addFileChildren(AuthedDashboardRouteRouteChildren)

interface AuthedRouteChildren {
  AuthedDashboardRouteRoute: typeof AuthedDashboardRouteRouteWithChildren
  AuthedCompleteRegistrationRoute: typeof AuthedCompleteRegistrationRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRouteRoute: AuthedDashboardRouteRouteWithChildren,
  AuthedCompleteRegistrationRoute: AuthedCompleteRegistrationRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthedRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/dashboard': typeof AuthedDashboardRouteRouteWithChildren
  '/forgot-password': typeof authenticationForgotPasswordRoute
  '/login': typeof authenticationLoginRoute
  '/register': typeof authenticationRegisterRoute
  '/reset-password': typeof authenticationResetPasswordRoute
  '/complete-registration': typeof AuthedCompleteRegistrationRoute
  '/coffee-shops/$slug': typeof CoffeeShopsSlugRoute
  '/dashboard/settings': typeof AuthedDashboardSettingsRoute
  '/dashboard/': typeof AuthedDashboardIndexRoute
  '/dashboard/management/events': typeof AuthedDashboardManagementEventsRoute
  '/dashboard/management/packages': typeof AuthedDashboardManagementPackagesRoute
  '/dashboard/management/reservations': typeof AuthedDashboardManagementReservationsRoute
  '/dashboard/management/setup': typeof AuthedDashboardManagementSetupRoute
  '/dashboard/management/spaces': typeof AuthedDashboardManagementSpacesRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthedRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/forgot-password': typeof authenticationForgotPasswordRoute
  '/login': typeof authenticationLoginRoute
  '/register': typeof authenticationRegisterRoute
  '/reset-password': typeof authenticationResetPasswordRoute
  '/complete-registration': typeof AuthedCompleteRegistrationRoute
  '/coffee-shops/$slug': typeof CoffeeShopsSlugRoute
  '/dashboard/settings': typeof AuthedDashboardSettingsRoute
  '/dashboard': typeof AuthedDashboardIndexRoute
  '/dashboard/management/events': typeof AuthedDashboardManagementEventsRoute
  '/dashboard/management/packages': typeof AuthedDashboardManagementPackagesRoute
  '/dashboard/management/reservations': typeof AuthedDashboardManagementReservationsRoute
  '/dashboard/management/setup': typeof AuthedDashboardManagementSetupRoute
  '/dashboard/management/spaces': typeof AuthedDashboardManagementSpacesRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_authed/dashboard': typeof AuthedDashboardRouteRouteWithChildren
  '/(authentication)/forgot-password': typeof authenticationForgotPasswordRoute
  '/(authentication)/login': typeof authenticationLoginRoute
  '/(authentication)/register': typeof authenticationRegisterRoute
  '/(authentication)/reset-password': typeof authenticationResetPasswordRoute
  '/_authed/complete-registration': typeof AuthedCompleteRegistrationRoute
  '/coffee-shops/$slug': typeof CoffeeShopsSlugRoute
  '/_authed/dashboard/settings': typeof AuthedDashboardSettingsRoute
  '/_authed/dashboard/': typeof AuthedDashboardIndexRoute
  '/_authed/dashboard/management/events': typeof AuthedDashboardManagementEventsRoute
  '/_authed/dashboard/management/packages': typeof AuthedDashboardManagementPackagesRoute
  '/_authed/dashboard/management/reservations': typeof AuthedDashboardManagementReservationsRoute
  '/_authed/dashboard/management/setup': typeof AuthedDashboardManagementSetupRoute
  '/_authed/dashboard/management/spaces': typeof AuthedDashboardManagementSpacesRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/privacy'
    | '/terms'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/complete-registration'
    | '/coffee-shops/$slug'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/management/events'
    | '/dashboard/management/packages'
    | '/dashboard/management/reservations'
    | '/dashboard/management/setup'
    | '/dashboard/management/spaces'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/privacy'
    | '/terms'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/complete-registration'
    | '/coffee-shops/$slug'
    | '/dashboard/settings'
    | '/dashboard'
    | '/dashboard/management/events'
    | '/dashboard/management/packages'
    | '/dashboard/management/reservations'
    | '/dashboard/management/setup'
    | '/dashboard/management/spaces'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/privacy'
    | '/terms'
    | '/_authed/dashboard'
    | '/(authentication)/forgot-password'
    | '/(authentication)/login'
    | '/(authentication)/register'
    | '/(authentication)/reset-password'
    | '/_authed/complete-registration'
    | '/coffee-shops/$slug'
    | '/_authed/dashboard/settings'
    | '/_authed/dashboard/'
    | '/_authed/dashboard/management/events'
    | '/_authed/dashboard/management/packages'
    | '/_authed/dashboard/management/reservations'
    | '/_authed/dashboard/management/setup'
    | '/_authed/dashboard/management/spaces'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  authenticationForgotPasswordRoute: typeof authenticationForgotPasswordRoute
  authenticationLoginRoute: typeof authenticationLoginRoute
  authenticationRegisterRoute: typeof authenticationRegisterRoute
  authenticationResetPasswordRoute: typeof authenticationResetPasswordRoute
  CoffeeShopsSlugRoute: typeof CoffeeShopsSlugRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  authenticationForgotPasswordRoute: authenticationForgotPasswordRoute,
  authenticationLoginRoute: authenticationLoginRoute,
  authenticationRegisterRoute: authenticationRegisterRoute,
  authenticationResetPasswordRoute: authenticationResetPasswordRoute,
  CoffeeShopsSlugRoute: CoffeeShopsSlugRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authed",
        "/privacy",
        "/terms",
        "/(authentication)/forgot-password",
        "/(authentication)/login",
        "/(authentication)/register",
        "/(authentication)/reset-password",
        "/coffee-shops/$slug"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authed": {
      "filePath": "_authed.tsx",
      "children": [
        "/_authed/dashboard",
        "/_authed/complete-registration"
      ]
    },
    "/privacy": {
      "filePath": "privacy.tsx"
    },
    "/terms": {
      "filePath": "terms.tsx"
    },
    "/_authed/dashboard": {
      "filePath": "_authed/dashboard/route.tsx",
      "parent": "/_authed",
      "children": [
        "/_authed/dashboard/settings",
        "/_authed/dashboard/",
        "/_authed/dashboard/management/events",
        "/_authed/dashboard/management/packages",
        "/_authed/dashboard/management/reservations",
        "/_authed/dashboard/management/setup",
        "/_authed/dashboard/management/spaces"
      ]
    },
    "/(authentication)/forgot-password": {
      "filePath": "(authentication)/forgot-password.tsx"
    },
    "/(authentication)/login": {
      "filePath": "(authentication)/login.tsx"
    },
    "/(authentication)/register": {
      "filePath": "(authentication)/register.tsx"
    },
    "/(authentication)/reset-password": {
      "filePath": "(authentication)/reset-password.tsx"
    },
    "/_authed/complete-registration": {
      "filePath": "_authed/complete-registration.tsx",
      "parent": "/_authed"
    },
    "/coffee-shops/$slug": {
      "filePath": "coffee-shops.$slug.tsx"
    },
    "/_authed/dashboard/settings": {
      "filePath": "_authed/dashboard/settings.tsx",
      "parent": "/_authed/dashboard"
    },
    "/_authed/dashboard/": {
      "filePath": "_authed/dashboard/index.tsx",
      "parent": "/_authed/dashboard"
    },
    "/_authed/dashboard/management/events": {
      "filePath": "_authed/dashboard/management/events.tsx",
      "parent": "/_authed/dashboard"
    },
    "/_authed/dashboard/management/packages": {
      "filePath": "_authed/dashboard/management/packages.tsx",
      "parent": "/_authed/dashboard"
    },
    "/_authed/dashboard/management/reservations": {
      "filePath": "_authed/dashboard/management/reservations.tsx",
      "parent": "/_authed/dashboard"
    },
    "/_authed/dashboard/management/setup": {
      "filePath": "_authed/dashboard/management/setup.tsx",
      "parent": "/_authed/dashboard"
    },
    "/_authed/dashboard/management/spaces": {
      "filePath": "_authed/dashboard/management/spaces.tsx",
      "parent": "/_authed/dashboard"
    }
  }
}
ROUTE_MANIFEST_END */
