/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AdminOrdersRouteImport } from './routes/_admin/orders'
import { Route as AdminListingsRouteImport } from './routes/_admin/listings'
import { Route as AdminDashboardRouteImport } from './routes/_admin/dashboard'
import { Route as DigitalHubProductsIndexRouteImport } from './routes/_digital-hub/products/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DigitalHubProductsIdRouteImport } from './routes/_digital-hub/products/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/_admin/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminListingsRoute = AdminListingsRouteImport.update({
  id: '/_admin/listings',
  path: '/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/_admin/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalHubProductsIndexRoute = DigitalHubProductsIndexRouteImport.update({
  id: '/_digital-hub/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalHubProductsIdRoute = DigitalHubProductsIdRouteImport.update({
  id: '/_digital-hub/products/$id',
  path: '/products/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AdminDashboardRoute
  '/listings': typeof AdminListingsRoute
  '/orders': typeof AdminOrdersRoute
  '/login': typeof AuthLoginRoute
  '/products/$id': typeof DigitalHubProductsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/products': typeof DigitalHubProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AdminDashboardRoute
  '/listings': typeof AdminListingsRoute
  '/orders': typeof AdminOrdersRoute
  '/login': typeof AuthLoginRoute
  '/products/$id': typeof DigitalHubProductsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/products': typeof DigitalHubProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin/dashboard': typeof AdminDashboardRoute
  '/_admin/listings': typeof AdminListingsRoute
  '/_admin/orders': typeof AdminOrdersRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_digital-hub/products/$id': typeof DigitalHubProductsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_digital-hub/products/': typeof DigitalHubProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/listings'
    | '/orders'
    | '/login'
    | '/products/$id'
    | '/api/auth/$'
    | '/products'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/listings'
    | '/orders'
    | '/login'
    | '/products/$id'
    | '/api/auth/$'
    | '/products'
  id:
    | '__root__'
    | '/'
    | '/_admin/dashboard'
    | '/_admin/listings'
    | '/_admin/orders'
    | '/_auth/login'
    | '/_digital-hub/products/$id'
    | '/api/auth/$'
    | '/_digital-hub/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminListingsRoute: typeof AdminListingsRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AuthLoginRoute: typeof AuthLoginRoute
  DigitalHubProductsIdRoute: typeof DigitalHubProductsIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  DigitalHubProductsIndexRoute: typeof DigitalHubProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/orders': {
      id: '/_admin/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/listings': {
      id: '/_admin/listings'
      path: '/listings'
      fullPath: '/listings'
      preLoaderRoute: typeof AdminListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_digital-hub/products/': {
      id: '/_digital-hub/products/'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof DigitalHubProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_digital-hub/products/$id': {
      id: '/_digital-hub/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof DigitalHubProductsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminListingsRoute: AdminListingsRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AuthLoginRoute: AuthLoginRoute,
  DigitalHubProductsIdRoute: DigitalHubProductsIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  DigitalHubProductsIndexRoute: DigitalHubProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
