/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExploreIndexRouteImport } from './routes/explore/index'
import { Route as AuthedWaitlistRouteImport } from './routes/_authed/waitlist'
import { Route as AuthedOnboardingRouteImport } from './routes/_authed/onboarding'
import { Route as AuthedCompleteRegistrationRouteImport } from './routes/_authed/complete-registration'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthedDashboardRouteRouteImport } from './routes/_authed/dashboard/route'
import { Route as AuthedDashboardIndexRouteImport } from './routes/_authed/dashboard/index'
import { Route as ApiNotificationsStreamRouteImport } from './routes/api/notifications.stream'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthedDashboardAdminRouteRouteImport } from './routes/_authed/dashboard/admin/route'
import { Route as AuthedDashboardUsersIndexRouteImport } from './routes/_authed/dashboard/users/index'
import { Route as AuthedDashboardRequestsIndexRouteImport } from './routes/_authed/dashboard/requests/index'
import { Route as AuthedDashboardQuotesIndexRouteImport } from './routes/_authed/dashboard/quotes/index'
import { Route as AuthedDashboardProfileIndexRouteImport } from './routes/_authed/dashboard/profile/index'
import { Route as AuthedDashboardOffersIndexRouteImport } from './routes/_authed/dashboard/offers/index'
import { Route as AuthedDashboardMarketplaceIndexRouteImport } from './routes/_authed/dashboard/marketplace/index'
import { Route as AuthedDashboardHistoryIndexRouteImport } from './routes/_authed/dashboard/history/index'
import { Route as AuthedDashboardGarageIndexRouteImport } from './routes/_authed/dashboard/garage/index'
import { Route as AuthedDashboardAuditIndexRouteImport } from './routes/_authed/dashboard/audit/index'
import { Route as AuthedDashboardRequestsRequestIdRouteImport } from './routes/_authed/dashboard/requests/$requestId'
import { Route as AuthedDashboardAdminSellersRouteImport } from './routes/_authed/dashboard/admin/sellers'
import { Route as AuthedDashboardAdminCategoriesRouteImport } from './routes/_authed/dashboard/admin/categories'
import { Route as AuthedDashboardAdminBuyersRouteImport } from './routes/_authed/dashboard/admin/buyers'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreIndexRoute = ExploreIndexRouteImport.update({
  id: '/explore/',
  path: '/explore/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedWaitlistRoute = AuthedWaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOnboardingRoute = AuthedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCompleteRegistrationRoute =
  AuthedCompleteRegistrationRouteImport.update({
    id: '/complete-registration',
    path: '/complete-registration',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardRouteRoute = AuthedDashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardIndexRoute = AuthedDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedDashboardRouteRoute,
} as any)
const ApiNotificationsStreamRoute = ApiNotificationsStreamRouteImport.update({
  id: '/api/notifications/stream',
  path: '/api/notifications/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardAdminRouteRoute =
  AuthedDashboardAdminRouteRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => AuthedDashboardRouteRoute,
  } as any)
const AuthedDashboardUsersIndexRoute =
  AuthedDashboardUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AuthedDashboardRouteRoute,
  } as any)
const AuthedDashboardRequestsIndexRoute =
  AuthedDashboardRequestsIndexRouteImport.update({
    id: '/requests/',
    path: '/requests/',
    getParentRoute: () => AuthedDashboardRouteRoute,
  } as any)
const AuthedDashboardQuotesIndexRoute =
  AuthedDashboardQuotesIndexRouteImport.update({
    id: '/quotes/',
    path: '/quotes/',
    getParentRoute: () => AuthedDashboardRouteRoute,
  } as any)
const AuthedDashboardProfileIndexRoute =
  AuthedDashboardProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => AuthedDashboardRouteRoute,
  } as any)
const AuthedDashboardOffersIndexRoute =
  AuthedDashboardOffersIndexRouteImport.update({
    id: '/offers/',
    path: '/offers/',
    getParentRoute: () => AuthedDashboardRouteRoute,
  } as any)
const AuthedDashboardMarketplaceIndexRoute =
  AuthedDashboardMarketplaceIndexRouteImport.update({
    id: '/marketplace/',
    path: '/marketplace/',
    getParentRoute: () => AuthedDashboardRouteRoute,
  } as any)
const AuthedDashboardHistoryIndexRoute =
  AuthedDashboardHistoryIndexRouteImport.update({
    id: '/history/',
    path: '/history/',
    getParentRoute: () => AuthedDashboardRouteRoute,
  } as any)
const AuthedDashboardGarageIndexRoute =
  AuthedDashboardGarageIndexRouteImport.update({
    id: '/garage/',
    path: '/garage/',
    getParentRoute: () => AuthedDashboardRouteRoute,
  } as any)
const AuthedDashboardAuditIndexRoute =
  AuthedDashboardAuditIndexRouteImport.update({
    id: '/audit/',
    path: '/audit/',
    getParentRoute: () => AuthedDashboardRouteRoute,
  } as any)
const AuthedDashboardRequestsRequestIdRoute =
  AuthedDashboardRequestsRequestIdRouteImport.update({
    id: '/requests/$requestId',
    path: '/requests/$requestId',
    getParentRoute: () => AuthedDashboardRouteRoute,
  } as any)
const AuthedDashboardAdminSellersRoute =
  AuthedDashboardAdminSellersRouteImport.update({
    id: '/sellers',
    path: '/sellers',
    getParentRoute: () => AuthedDashboardAdminRouteRoute,
  } as any)
const AuthedDashboardAdminCategoriesRoute =
  AuthedDashboardAdminCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthedDashboardAdminRouteRoute,
  } as any)
const AuthedDashboardAdminBuyersRoute =
  AuthedDashboardAdminBuyersRouteImport.update({
    id: '/buyers',
    path: '/buyers',
    getParentRoute: () => AuthedDashboardAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthedDashboardRouteRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/complete-registration': typeof AuthedCompleteRegistrationRoute
  '/onboarding': typeof AuthedOnboardingRoute
  '/waitlist': typeof AuthedWaitlistRoute
  '/explore/': typeof ExploreIndexRoute
  '/dashboard/admin': typeof AuthedDashboardAdminRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/notifications/stream': typeof ApiNotificationsStreamRoute
  '/dashboard/': typeof AuthedDashboardIndexRoute
  '/dashboard/admin/buyers': typeof AuthedDashboardAdminBuyersRoute
  '/dashboard/admin/categories': typeof AuthedDashboardAdminCategoriesRoute
  '/dashboard/admin/sellers': typeof AuthedDashboardAdminSellersRoute
  '/dashboard/requests/$requestId': typeof AuthedDashboardRequestsRequestIdRoute
  '/dashboard/audit/': typeof AuthedDashboardAuditIndexRoute
  '/dashboard/garage/': typeof AuthedDashboardGarageIndexRoute
  '/dashboard/history/': typeof AuthedDashboardHistoryIndexRoute
  '/dashboard/marketplace/': typeof AuthedDashboardMarketplaceIndexRoute
  '/dashboard/offers/': typeof AuthedDashboardOffersIndexRoute
  '/dashboard/profile/': typeof AuthedDashboardProfileIndexRoute
  '/dashboard/quotes/': typeof AuthedDashboardQuotesIndexRoute
  '/dashboard/requests/': typeof AuthedDashboardRequestsIndexRoute
  '/dashboard/users/': typeof AuthedDashboardUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/complete-registration': typeof AuthedCompleteRegistrationRoute
  '/onboarding': typeof AuthedOnboardingRoute
  '/waitlist': typeof AuthedWaitlistRoute
  '/explore': typeof ExploreIndexRoute
  '/dashboard/admin': typeof AuthedDashboardAdminRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/notifications/stream': typeof ApiNotificationsStreamRoute
  '/dashboard': typeof AuthedDashboardIndexRoute
  '/dashboard/admin/buyers': typeof AuthedDashboardAdminBuyersRoute
  '/dashboard/admin/categories': typeof AuthedDashboardAdminCategoriesRoute
  '/dashboard/admin/sellers': typeof AuthedDashboardAdminSellersRoute
  '/dashboard/requests/$requestId': typeof AuthedDashboardRequestsRequestIdRoute
  '/dashboard/audit': typeof AuthedDashboardAuditIndexRoute
  '/dashboard/garage': typeof AuthedDashboardGarageIndexRoute
  '/dashboard/history': typeof AuthedDashboardHistoryIndexRoute
  '/dashboard/marketplace': typeof AuthedDashboardMarketplaceIndexRoute
  '/dashboard/offers': typeof AuthedDashboardOffersIndexRoute
  '/dashboard/profile': typeof AuthedDashboardProfileIndexRoute
  '/dashboard/quotes': typeof AuthedDashboardQuotesIndexRoute
  '/dashboard/requests': typeof AuthedDashboardRequestsIndexRoute
  '/dashboard/users': typeof AuthedDashboardUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/_authed/dashboard': typeof AuthedDashboardRouteRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_authed/complete-registration': typeof AuthedCompleteRegistrationRoute
  '/_authed/onboarding': typeof AuthedOnboardingRoute
  '/_authed/waitlist': typeof AuthedWaitlistRoute
  '/explore/': typeof ExploreIndexRoute
  '/_authed/dashboard/admin': typeof AuthedDashboardAdminRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/notifications/stream': typeof ApiNotificationsStreamRoute
  '/_authed/dashboard/': typeof AuthedDashboardIndexRoute
  '/_authed/dashboard/admin/buyers': typeof AuthedDashboardAdminBuyersRoute
  '/_authed/dashboard/admin/categories': typeof AuthedDashboardAdminCategoriesRoute
  '/_authed/dashboard/admin/sellers': typeof AuthedDashboardAdminSellersRoute
  '/_authed/dashboard/requests/$requestId': typeof AuthedDashboardRequestsRequestIdRoute
  '/_authed/dashboard/audit/': typeof AuthedDashboardAuditIndexRoute
  '/_authed/dashboard/garage/': typeof AuthedDashboardGarageIndexRoute
  '/_authed/dashboard/history/': typeof AuthedDashboardHistoryIndexRoute
  '/_authed/dashboard/marketplace/': typeof AuthedDashboardMarketplaceIndexRoute
  '/_authed/dashboard/offers/': typeof AuthedDashboardOffersIndexRoute
  '/_authed/dashboard/profile/': typeof AuthedDashboardProfileIndexRoute
  '/_authed/dashboard/quotes/': typeof AuthedDashboardQuotesIndexRoute
  '/_authed/dashboard/requests/': typeof AuthedDashboardRequestsIndexRoute
  '/_authed/dashboard/users/': typeof AuthedDashboardUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/complete-registration'
    | '/onboarding'
    | '/waitlist'
    | '/explore/'
    | '/dashboard/admin'
    | '/api/auth/$'
    | '/api/notifications/stream'
    | '/dashboard/'
    | '/dashboard/admin/buyers'
    | '/dashboard/admin/categories'
    | '/dashboard/admin/sellers'
    | '/dashboard/requests/$requestId'
    | '/dashboard/audit/'
    | '/dashboard/garage/'
    | '/dashboard/history/'
    | '/dashboard/marketplace/'
    | '/dashboard/offers/'
    | '/dashboard/profile/'
    | '/dashboard/quotes/'
    | '/dashboard/requests/'
    | '/dashboard/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/complete-registration'
    | '/onboarding'
    | '/waitlist'
    | '/explore'
    | '/dashboard/admin'
    | '/api/auth/$'
    | '/api/notifications/stream'
    | '/dashboard'
    | '/dashboard/admin/buyers'
    | '/dashboard/admin/categories'
    | '/dashboard/admin/sellers'
    | '/dashboard/requests/$requestId'
    | '/dashboard/audit'
    | '/dashboard/garage'
    | '/dashboard/history'
    | '/dashboard/marketplace'
    | '/dashboard/offers'
    | '/dashboard/profile'
    | '/dashboard/quotes'
    | '/dashboard/requests'
    | '/dashboard/users'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_authed/dashboard'
    | '/_auth/login'
    | '/_authed/complete-registration'
    | '/_authed/onboarding'
    | '/_authed/waitlist'
    | '/explore/'
    | '/_authed/dashboard/admin'
    | '/api/auth/$'
    | '/api/notifications/stream'
    | '/_authed/dashboard/'
    | '/_authed/dashboard/admin/buyers'
    | '/_authed/dashboard/admin/categories'
    | '/_authed/dashboard/admin/sellers'
    | '/_authed/dashboard/requests/$requestId'
    | '/_authed/dashboard/audit/'
    | '/_authed/dashboard/garage/'
    | '/_authed/dashboard/history/'
    | '/_authed/dashboard/marketplace/'
    | '/_authed/dashboard/offers/'
    | '/_authed/dashboard/profile/'
    | '/_authed/dashboard/quotes/'
    | '/_authed/dashboard/requests/'
    | '/_authed/dashboard/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  ExploreIndexRoute: typeof ExploreIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiNotificationsStreamRoute: typeof ApiNotificationsStreamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/': {
      id: '/explore/'
      path: '/explore'
      fullPath: '/explore/'
      preLoaderRoute: typeof ExploreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/waitlist': {
      id: '/_authed/waitlist'
      path: '/waitlist'
      fullPath: '/waitlist'
      preLoaderRoute: typeof AuthedWaitlistRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/onboarding': {
      id: '/_authed/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthedOnboardingRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/complete-registration': {
      id: '/_authed/complete-registration'
      path: '/complete-registration'
      fullPath: '/complete-registration'
      preLoaderRoute: typeof AuthedCompleteRegistrationRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard/': {
      id: '/_authed/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthedDashboardIndexRouteImport
      parentRoute: typeof AuthedDashboardRouteRoute
    }
    '/api/notifications/stream': {
      id: '/api/notifications/stream'
      path: '/api/notifications/stream'
      fullPath: '/api/notifications/stream'
      preLoaderRoute: typeof ApiNotificationsStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard/admin': {
      id: '/_authed/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof AuthedDashboardAdminRouteRouteImport
      parentRoute: typeof AuthedDashboardRouteRoute
    }
    '/_authed/dashboard/users/': {
      id: '/_authed/dashboard/users/'
      path: '/users'
      fullPath: '/dashboard/users/'
      preLoaderRoute: typeof AuthedDashboardUsersIndexRouteImport
      parentRoute: typeof AuthedDashboardRouteRoute
    }
    '/_authed/dashboard/requests/': {
      id: '/_authed/dashboard/requests/'
      path: '/requests'
      fullPath: '/dashboard/requests/'
      preLoaderRoute: typeof AuthedDashboardRequestsIndexRouteImport
      parentRoute: typeof AuthedDashboardRouteRoute
    }
    '/_authed/dashboard/quotes/': {
      id: '/_authed/dashboard/quotes/'
      path: '/quotes'
      fullPath: '/dashboard/quotes/'
      preLoaderRoute: typeof AuthedDashboardQuotesIndexRouteImport
      parentRoute: typeof AuthedDashboardRouteRoute
    }
    '/_authed/dashboard/profile/': {
      id: '/_authed/dashboard/profile/'
      path: '/profile'
      fullPath: '/dashboard/profile/'
      preLoaderRoute: typeof AuthedDashboardProfileIndexRouteImport
      parentRoute: typeof AuthedDashboardRouteRoute
    }
    '/_authed/dashboard/offers/': {
      id: '/_authed/dashboard/offers/'
      path: '/offers'
      fullPath: '/dashboard/offers/'
      preLoaderRoute: typeof AuthedDashboardOffersIndexRouteImport
      parentRoute: typeof AuthedDashboardRouteRoute
    }
    '/_authed/dashboard/marketplace/': {
      id: '/_authed/dashboard/marketplace/'
      path: '/marketplace'
      fullPath: '/dashboard/marketplace/'
      preLoaderRoute: typeof AuthedDashboardMarketplaceIndexRouteImport
      parentRoute: typeof AuthedDashboardRouteRoute
    }
    '/_authed/dashboard/history/': {
      id: '/_authed/dashboard/history/'
      path: '/history'
      fullPath: '/dashboard/history/'
      preLoaderRoute: typeof AuthedDashboardHistoryIndexRouteImport
      parentRoute: typeof AuthedDashboardRouteRoute
    }
    '/_authed/dashboard/garage/': {
      id: '/_authed/dashboard/garage/'
      path: '/garage'
      fullPath: '/dashboard/garage/'
      preLoaderRoute: typeof AuthedDashboardGarageIndexRouteImport
      parentRoute: typeof AuthedDashboardRouteRoute
    }
    '/_authed/dashboard/audit/': {
      id: '/_authed/dashboard/audit/'
      path: '/audit'
      fullPath: '/dashboard/audit/'
      preLoaderRoute: typeof AuthedDashboardAuditIndexRouteImport
      parentRoute: typeof AuthedDashboardRouteRoute
    }
    '/_authed/dashboard/requests/$requestId': {
      id: '/_authed/dashboard/requests/$requestId'
      path: '/requests/$requestId'
      fullPath: '/dashboard/requests/$requestId'
      preLoaderRoute: typeof AuthedDashboardRequestsRequestIdRouteImport
      parentRoute: typeof AuthedDashboardRouteRoute
    }
    '/_authed/dashboard/admin/sellers': {
      id: '/_authed/dashboard/admin/sellers'
      path: '/sellers'
      fullPath: '/dashboard/admin/sellers'
      preLoaderRoute: typeof AuthedDashboardAdminSellersRouteImport
      parentRoute: typeof AuthedDashboardAdminRouteRoute
    }
    '/_authed/dashboard/admin/categories': {
      id: '/_authed/dashboard/admin/categories'
      path: '/categories'
      fullPath: '/dashboard/admin/categories'
      preLoaderRoute: typeof AuthedDashboardAdminCategoriesRouteImport
      parentRoute: typeof AuthedDashboardAdminRouteRoute
    }
    '/_authed/dashboard/admin/buyers': {
      id: '/_authed/dashboard/admin/buyers'
      path: '/buyers'
      fullPath: '/dashboard/admin/buyers'
      preLoaderRoute: typeof AuthedDashboardAdminBuyersRouteImport
      parentRoute: typeof AuthedDashboardAdminRouteRoute
    }
  }
}

interface AuthedDashboardAdminRouteRouteChildren {
  AuthedDashboardAdminBuyersRoute: typeof AuthedDashboardAdminBuyersRoute
  AuthedDashboardAdminCategoriesRoute: typeof AuthedDashboardAdminCategoriesRoute
  AuthedDashboardAdminSellersRoute: typeof AuthedDashboardAdminSellersRoute
}

const AuthedDashboardAdminRouteRouteChildren: AuthedDashboardAdminRouteRouteChildren =
  {
    AuthedDashboardAdminBuyersRoute: AuthedDashboardAdminBuyersRoute,
    AuthedDashboardAdminCategoriesRoute: AuthedDashboardAdminCategoriesRoute,
    AuthedDashboardAdminSellersRoute: AuthedDashboardAdminSellersRoute,
  }

const AuthedDashboardAdminRouteRouteWithChildren =
  AuthedDashboardAdminRouteRoute._addFileChildren(
    AuthedDashboardAdminRouteRouteChildren,
  )

interface AuthedDashboardRouteRouteChildren {
  AuthedDashboardAdminRouteRoute: typeof AuthedDashboardAdminRouteRouteWithChildren
  AuthedDashboardIndexRoute: typeof AuthedDashboardIndexRoute
  AuthedDashboardRequestsRequestIdRoute: typeof AuthedDashboardRequestsRequestIdRoute
  AuthedDashboardAuditIndexRoute: typeof AuthedDashboardAuditIndexRoute
  AuthedDashboardGarageIndexRoute: typeof AuthedDashboardGarageIndexRoute
  AuthedDashboardHistoryIndexRoute: typeof AuthedDashboardHistoryIndexRoute
  AuthedDashboardMarketplaceIndexRoute: typeof AuthedDashboardMarketplaceIndexRoute
  AuthedDashboardOffersIndexRoute: typeof AuthedDashboardOffersIndexRoute
  AuthedDashboardProfileIndexRoute: typeof AuthedDashboardProfileIndexRoute
  AuthedDashboardQuotesIndexRoute: typeof AuthedDashboardQuotesIndexRoute
  AuthedDashboardRequestsIndexRoute: typeof AuthedDashboardRequestsIndexRoute
  AuthedDashboardUsersIndexRoute: typeof AuthedDashboardUsersIndexRoute
}

const AuthedDashboardRouteRouteChildren: AuthedDashboardRouteRouteChildren = {
  AuthedDashboardAdminRouteRoute: AuthedDashboardAdminRouteRouteWithChildren,
  AuthedDashboardIndexRoute: AuthedDashboardIndexRoute,
  AuthedDashboardRequestsRequestIdRoute: AuthedDashboardRequestsRequestIdRoute,
  AuthedDashboardAuditIndexRoute: AuthedDashboardAuditIndexRoute,
  AuthedDashboardGarageIndexRoute: AuthedDashboardGarageIndexRoute,
  AuthedDashboardHistoryIndexRoute: AuthedDashboardHistoryIndexRoute,
  AuthedDashboardMarketplaceIndexRoute: AuthedDashboardMarketplaceIndexRoute,
  AuthedDashboardOffersIndexRoute: AuthedDashboardOffersIndexRoute,
  AuthedDashboardProfileIndexRoute: AuthedDashboardProfileIndexRoute,
  AuthedDashboardQuotesIndexRoute: AuthedDashboardQuotesIndexRoute,
  AuthedDashboardRequestsIndexRoute: AuthedDashboardRequestsIndexRoute,
  AuthedDashboardUsersIndexRoute: AuthedDashboardUsersIndexRoute,
}

const AuthedDashboardRouteRouteWithChildren =
  AuthedDashboardRouteRoute._addFileChildren(AuthedDashboardRouteRouteChildren)

interface AuthedRouteChildren {
  AuthedDashboardRouteRoute: typeof AuthedDashboardRouteRouteWithChildren
  AuthedCompleteRegistrationRoute: typeof AuthedCompleteRegistrationRoute
  AuthedOnboardingRoute: typeof AuthedOnboardingRoute
  AuthedWaitlistRoute: typeof AuthedWaitlistRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRouteRoute: AuthedDashboardRouteRouteWithChildren,
  AuthedCompleteRegistrationRoute: AuthedCompleteRegistrationRoute,
  AuthedOnboardingRoute: AuthedOnboardingRoute,
  AuthedWaitlistRoute: AuthedWaitlistRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  ExploreIndexRoute: ExploreIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiNotificationsStreamRoute: ApiNotificationsStreamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
